apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: helloworld-backend
spec:
  ports:
  - port: 80
    nodePort: 31479
    protocol: TCP
    targetPort: 80
  selector:
    run: helloworld-backend
  type: LoadBalancer
